package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	goruntime "runtime"
	"strings"
)

// providerEnvVarName builds: {厂家名称}_api_key
// e.g. deepseek → deepseek_api_key, OpenAI → openai_api_key
func providerEnvVarName(providerID, displayName string) string {
	base := slugify(providerID)
	if base == "" || base == "custom" {
		if n := slugify(displayName); n != "" {
			base = n
		}
	}
	if base == "" {
		base = "custom"
	}
	// User rule: 厂家名称_api_key
	return strings.ToLower(base) + "_api_key"
}

// setSystemEnvVar sets a user-level environment variable so new processes can see it.
// Also sets the variable for the current process.
func setSystemEnvVar(name, value string) error {
	name = strings.TrimSpace(name)
	if name == "" {
		return fmt.Errorf("环境变量名为空")
	}
	if !looksLikeEnvVarName(name) {
		return fmt.Errorf("非法环境变量名: %s", name)
	}

	// 1) current process (immediate for this app / children)
	if err := os.Setenv(name, value); err != nil {
		return err
	}

	// 2) durable store + shell export file
	// secrets map key = env var name
	if err := upsertSecretMap(name, value); err != nil {
		_ = err
	}
	if err := writeProvidersEnvFile(); err != nil {
		_ = err
	}

	// 3) OS-specific user environment
	switch goruntime.GOOS {
	case "darwin":
		return setEnvDarwin(name, value)
	case "windows":
		return setEnvWindows(name, value)
	default:
		return setEnvUnixProfile(name, value)
	}
}

// writeProvidersEnvFile regenerates ~/.codex-manager/env/providers.env from secrets.json
// and ensures shell profiles source it.
func writeProvidersEnvFile() error {
	dir := filepath.Join(managerRoot(), "env")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	secPath := filepath.Join(dir, "secrets.json")
	secrets := map[string]string{}
	if b, err := os.ReadFile(secPath); err == nil {
		_ = jsonUnmarshalSecrets(b, &secrets)
	}

	var lines []string
	lines = append(lines, "# Auto-generated by Codex model manager — do not commit")
	lines = append(lines, "# Sourced by shell profile so Codex CLI sees keys")
	keys := sortedSecretKeys(secrets)
	for _, k := range keys {
		v := secrets[k]
		v = strings.ReplaceAll(v, `'`, `'"'"'`)
		lines = append(lines, fmt.Sprintf("export %s='%s'", k, v))
	}
	envFile := filepath.Join(dir, "providers.env")
	if err := os.WriteFile(envFile, []byte(strings.Join(lines, "\n")+"\n"), 0o600); err != nil {
		return err
	}

	// ensure profiles source this file
	_ = ensureShellSourcesEnvFile(envFile)
	return nil
}

func jsonUnmarshalSecrets(b []byte, out *map[string]string) error {
	return json.Unmarshal(b, out)
}

func upsertSecretMap(envName, value string) error {
	dir := filepath.Join(managerRoot(), "env")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	secPath := filepath.Join(dir, "secrets.json")
	secrets := map[string]string{}
	if b, err := os.ReadFile(secPath); err == nil {
		_ = json.Unmarshal(b, &secrets)
	}
	secrets[envName] = value
	b, err := json.MarshalIndent(secrets, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(secPath, b, 0o600)
}

// setEnvDarwin: launchctl (GUI apps) + shell profile source
func setEnvDarwin(name, value string) error {
	// launchctl setenv — affects apps launched from Finder after re-login/new session
	// Note: does not affect already-running terminals until restart
	cmd := exec.Command("launchctl", "setenv", name, value)
	_ = cmd.Run() // best-effort; may fail in sandbox

	// Also write into user launch agent plist for persistence across reboot
	_ = writeLaunchAgentEnv()

	// shell profile for Terminal/iTerm
	return ensureShellSourcesEnvFile(filepath.Join(managerRoot(), "env", "providers.env"))
}

// writeLaunchAgentEnv creates a LaunchAgent that exports all managed keys at login.
func writeLaunchAgentEnv() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	envFile := filepath.Join(managerRoot(), "env", "providers.env")
	agents := filepath.Join(home, "Library", "LaunchAgents")
	if err := os.MkdirAll(agents, 0o755); err != nil {
		return err
	}
	plistPath := filepath.Join(agents, "com.codex.manager.env.plist")
	// Use a small shell to source providers.env and launchctl setenv each key
	script := filepath.Join(managerRoot(), "env", "apply-launchctl.sh")
	scriptBody := `#!/bin/zsh
ENV_FILE="` + envFile + `"
[[ -f "$ENV_FILE" ]] || exit 0
set -a
source "$ENV_FILE"
set +a
# push into launchctl domain for GUI apps
while IFS= read -r line; do
  case "$line" in
    export\ *=*)
      line="${line#export }"
      key="${line%%=*}"
      val="${line#*=}"
      val="${val#\'}"
      val="${val%\'}"
      /bin/launchctl setenv "$key" "$val" 2>/dev/null || true
      ;;
  esac
done < "$ENV_FILE"
`
	if err := os.WriteFile(script, []byte(scriptBody), 0o700); err != nil {
		return err
	}
	plist := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.codex.manager.env</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/zsh</string>
    <string>%s</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
`, script)
	if err := os.WriteFile(plistPath, []byte(plist), 0o644); err != nil {
		return err
	}
	// load / reload agent
	_ = exec.Command("launchctl", "unload", plistPath).Run()
	_ = exec.Command("launchctl", "load", plistPath).Run()
	// apply now
	_ = exec.Command("/bin/zsh", script).Run()
	return nil
}

func setEnvWindows(name, value string) error {
	// Permanent user environment via setx (new processes only)
	// setx truncates at 1024 chars — API keys are usually fine
	cmd := exec.Command("setx", name, value)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("setx failed: %v (%s)", err, strings.TrimSpace(string(out)))
	}
	// Also set for current process already done via os.Setenv
	return nil
}

func setEnvUnixProfile(name, value string) error {
	return ensureShellSourcesEnvFile(filepath.Join(managerRoot(), "env", "providers.env"))
}

var sourceLineRe = regexp.MustCompile(`codex-manager/env/providers\.env`)

func ensureShellSourcesEnvFile(envFile string) error {
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		return err
	}
	// Absolute path for source line
	abs := envFile
	if a, e := filepath.Abs(envFile); e == nil {
		abs = a
	}
	marker := `# >>> codex-manager env >>>`
	block := marker + "\n" +
		`[ -f "` + abs + `" ] && . "` + abs + `"` + "\n" +
		`# <<< codex-manager env <<<` + "\n"

	profiles := []string{
		filepath.Join(home, ".zprofile"),
		filepath.Join(home, ".zshrc"),
		filepath.Join(home, ".bash_profile"),
		filepath.Join(home, ".profile"),
	}
	// Prefer writing to .zprofile on macOS (login shells), .profile on others
	targets := profiles
	if goruntime.GOOS == "darwin" {
		targets = []string{filepath.Join(home, ".zprofile"), filepath.Join(home, ".zshrc")}
	}

	for _, p := range targets {
		if err := upsertProfileBlock(p, marker, block); err != nil {
			continue
		}
	}
	return nil
}

func upsertProfileBlock(path, marker, block string) error {
	var content string
	b, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		content = ""
	} else {
		content = string(b)
	}
	if strings.Contains(content, marker) {
		// replace existing block
		start := strings.Index(content, marker)
		endMarker := `# <<< codex-manager env <<<`
		end := strings.Index(content[start:], endMarker)
		if end >= 0 {
			end = start + end + len(endMarker)
			// include trailing newline
			if end < len(content) && content[end] == '\n' {
				end++
			}
			content = content[:start] + block + content[end:]
		} else {
			content = content[:start] + block
		}
	} else {
		if content != "" && !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		content += "\n" + block
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func removeManagedProfileBlock(path string) error {
	b, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	content := string(b)
	marker := `# >>> codex-manager env >>>`
	endMarker := `# <<< codex-manager env <<<`
	start := strings.Index(content, marker)
	if start < 0 {
		return nil
	}
	end := strings.Index(content[start:], endMarker)
	if end < 0 {
		return nil
	}
	end = start + end + len(endMarker)
	if end < len(content) && content[end] == '\n' {
		end++
	}
	content = content[:start] + content[end:]
	return os.WriteFile(path, []byte(content), 0o644)
}

func setLaunchctlEnv(name, value string) {
	if goruntime.GOOS == "darwin" {
		_ = exec.Command("launchctl", "setenv", name, value).Run()
	}
}

func unsetLaunchctlEnv(name string) {
	if goruntime.GOOS == "darwin" {
		_ = exec.Command("launchctl", "unsetenv", name).Run()
	}
}

func restoreEnvironmentBackup(meta backupMeta) error {
	return restoreEnvironmentBackupPath(meta.EnvBackupPath)
}

func restoreEnvironmentBackupPath(envBackupPath string) error {
	if envBackupPath == "" {
		return nil
	}
	raw, err := os.ReadFile(envBackupPath)
	if err != nil {
		return fmt.Errorf("读取环境备份失败: %w", err)
	}
	var backup environmentBackup
	if err := json.Unmarshal(raw, &backup); err != nil {
		return fmt.Errorf("解析环境备份失败: %w", err)
	}

	secretsPath := filepath.Join(managerRoot(), "env", "secrets.json")
	current := map[string]string{}
	if raw, err := os.ReadFile(secretsPath); err == nil {
		_ = json.Unmarshal(raw, &current)
	}
	restored := map[string]string{}
	if backup.SecretsExists {
		_ = json.Unmarshal(backup.Secrets, &restored)
	}
	for name := range current {
		if strings.HasPrefix(name, "_") || !looksLikeEnvVarName(name) {
			continue
		}
		if _, ok := restored[name]; !ok {
			_ = os.Unsetenv(name)
			unsetLaunchctlEnv(name)
		}
	}
	for name, value := range restored {
		if strings.HasPrefix(name, "_") || !looksLikeEnvVarName(name) {
			continue
		}
		_ = os.Setenv(name, value)
		setLaunchctlEnv(name, value)
	}

	if backup.SecretsExists {
		if err := os.MkdirAll(filepath.Dir(secretsPath), 0o700); err != nil {
			return err
		}
		if err := os.WriteFile(secretsPath, backup.Secrets, 0o600); err != nil {
			return err
		}
	} else {
		_ = os.Remove(secretsPath)
	}
	providersPath := filepath.Join(managerRoot(), "env", "providers.env")
	if backup.ProvidersEnvExists {
		if err := os.MkdirAll(filepath.Dir(providersPath), 0o700); err != nil {
			return err
		}
		if err := os.WriteFile(providersPath, backup.ProvidersEnv, 0o600); err != nil {
			return err
		}
	} else {
		_ = os.Remove(providersPath)
	}
	for _, path := range managerEnvProfilePaths() {
		if !backup.ProfileHadManagerBlock[path] {
			_ = removeManagedProfileBlock(path)
		}
	}
	if !backup.SecretsExists && !backup.ProvidersEnvExists {
		home, _ := os.UserHomeDir()
		_ = os.Remove(filepath.Join(home, "Library", "LaunchAgents", "com.codex.manager.env.plist"))
		_ = os.Remove(filepath.Join(managerRoot(), "env", "apply-launchctl.sh"))
	}
	return nil
}

func sortedSecretKeys(secrets map[string]string) []string {
	keys := make([]string, 0, len(secrets))
	for k := range secrets {
		if strings.HasPrefix(k, "_") {
			continue
		}
		// only export real env-looking keys
		if !looksLikeEnvVarName(k) {
			continue
		}
		keys = append(keys, k)
	}
	for i := 0; i < len(keys); i++ {
		for j := i + 1; j < len(keys); j++ {
			if keys[j] < keys[i] {
				keys[i], keys[j] = keys[j], keys[i]
			}
		}
	}
	return keys
}
