package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	goruntime "runtime"
	"strings"
)

func looksLikeEnvVarName(s string) bool {
	s = strings.TrimSpace(s)
	if s == "" || len(s) > 80 {
		return false
	}
	low := strings.ToLower(s)
	if strings.HasPrefix(low, "sk-") || strings.HasPrefix(low, "rk-") {
		return false
	}
	for i, r := range s {
		if !((r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_') {
			return false
		}
		if i == 0 && r >= '0' && r <= '9' {
			return false
		}
	}
	return true
}

func setSystemEnvVar(name, value string) error {
	name = strings.TrimSpace(name)
	if name == "" || !looksLikeEnvVarName(name) {
		return fmt.Errorf("非法环境变量名: %s", name)
	}
	_ = os.Setenv(name, value)
	_ = upsertSecretMap(name, value)
	_ = writeProvidersEnvFile()

	switch goruntime.GOOS {
	case "darwin":
		_ = exec.Command("launchctl", "setenv", name, value).Run()
		return ensureShellSourcesEnvFile(filepath.Join(managerRoot(), "env", "providers.env"))
	case "windows":
		cmd := exec.Command("setx", name, value)
		if out, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("setx: %v (%s)", err, strings.TrimSpace(string(out)))
		}
		return nil
	default:
		return ensureShellSourcesEnvFile(filepath.Join(managerRoot(), "env", "providers.env"))
	}
}

func upsertSecretMap(envName, value string) error {
	dir := filepath.Join(managerRoot(), "env")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	secPath := filepath.Join(dir, "secrets.json")
	secrets := map[string]string{}
	if b, err := os.ReadFile(secPath); err == nil {
		_ = json.Unmarshal(b, &secrets)
	}
	secrets[envName] = value
	b, err := json.MarshalIndent(secrets, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(secPath, b, 0o600)
}

func writeProvidersEnvFile() error {
	dir := filepath.Join(managerRoot(), "env")
	_ = os.MkdirAll(dir, 0o700)
	secPath := filepath.Join(dir, "secrets.json")
	secrets := map[string]string{}
	if b, err := os.ReadFile(secPath); err == nil {
		_ = json.Unmarshal(b, &secrets)
	}
	var lines []string
	lines = append(lines, "# Auto-generated by Codex model manager")
	keys := make([]string, 0, len(secrets))
	for k := range secrets {
		if strings.HasPrefix(k, "_") || !looksLikeEnvVarName(k) {
			continue
		}
		keys = append(keys, k)
	}
	// sort
	for i := 0; i < len(keys); i++ {
		for j := i + 1; j < len(keys); j++ {
			if keys[j] < keys[i] {
				keys[i], keys[j] = keys[j], keys[i]
			}
		}
	}
	for _, k := range keys {
		v := strings.ReplaceAll(secrets[k], `'`, `'"'"'`)
		lines = append(lines, fmt.Sprintf("export %s='%s'", k, v))
	}
	return os.WriteFile(filepath.Join(dir, "providers.env"), []byte(strings.Join(lines, "\n")+"\n"), 0o600)
}

func ensureShellSourcesEnvFile(envFile string) error {
	home := userHome()
	if home == "" {
		return nil
	}
	abs := envFile
	if a, e := filepath.Abs(envFile); e == nil {
		abs = a
	}
	marker := `# >>> codex-manager env >>>`
	block := marker + "\n" + `[ -f "` + abs + `" ] && . "` + abs + `"` + "\n" + `# <<< codex-manager env <<<` + "\n"
	targets := []string{filepath.Join(home, ".zprofile"), filepath.Join(home, ".zshrc"), filepath.Join(home, ".profile")}
	if goruntime.GOOS != "darwin" {
		targets = []string{filepath.Join(home, ".profile"), filepath.Join(home, ".bashrc")}
	}
	for _, p := range targets {
		_ = upsertProfileBlock(p, marker, block)
	}
	return nil
}

func upsertProfileBlock(path, marker, block string) error {
	var content string
	b, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
	} else {
		content = string(b)
	}
	if strings.Contains(content, marker) {
		start := strings.Index(content, marker)
		endMarker := `# <<< codex-manager env <<<`
		end := strings.Index(content[start:], endMarker)
		if end >= 0 {
			end = start + end + len(endMarker)
			if end < len(content) && content[end] == '\n' {
				end++
			}
			content = content[:start] + block + content[end:]
		}
	} else {
		if content != "" && !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		content += "\n" + block
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

// silence unused import if any
var _ = regexp.MustCompile
