// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyDeepSeekClaudeCode(arg1:main.ClaudeDeepSeekRequest):Promise<main.ToolConfigStatus>;

export function ApplyProxyToCodex(arg1:string,arg2:string):Promise<main.ToolConfigStatus>;

export function ApplyToolModel(arg1:main.ModelApplyRequest):Promise<main.ToolConfigStatus>;

export function BackupDefaultConfig(arg1:string,arg2:string):Promise<main.ToolConfigStatus>;

export function ClearDefaultBackup(arg1:string):Promise<main.ToolConfigStatus>;

export function ClearToolConfigPath(arg1:string):Promise<main.ToolConfigStatus>;

export function ClearUsageStats():Promise<main.UsageStats>;

export function DeleteProvider(arg1:string):Promise<Array<main.Provider>>;

export function DiscoverToolConfigs():Promise<Array<main.ToolConfigStatus>>;

export function EnsureProxyRouting():Promise<main.ProxyStatus>;

export function FetchProviderModels(arg1:string,arg2:string):Promise<Array<main.FetchModelItem>>;

export function GetProviderPackageStatuses():Promise<Array<main.ProviderPackageStatus>>;

export function GetProxyConfig():Promise<main.ProxyConfig>;

export function GetProxyStatus():Promise<main.ProxyStatus>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetToolConfig(arg1:string):Promise<main.ToolConfigStatus>;

export function GetUsageStats():Promise<main.UsageStats>;

export function InjectGateway(arg1:string):Promise<main.ToolConfigStatus>;

export function ListModelGroups():Promise<Array<main.ModelGroupView>>;

export function ListProviders():Promise<Array<main.Provider>>;

export function PickToolConfig(arg1:string):Promise<main.ToolConfigStatus>;

export function ReadConfigText(arg1:string):Promise<string>;

export function RestoreCodexOriginalBases():Promise<main.ToolConfigStatus>;

export function RestoreDefaultConfig(arg1:string):Promise<main.ToolConfigStatus>;

export function RevealConfigPath(arg1:string):Promise<void>;

export function RollbackGateway(arg1:string):Promise<main.ToolConfigStatus>;

export function SaveProviders(arg1:Array<main.Provider>):Promise<void>;

export function SaveProxyConfig(arg1:main.ProxyConfig):Promise<main.ProxyStatus>;

export function SetModelGroupRouteEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetModelGroupRoutePriority(arg1:string,arg2:number):Promise<void>;

export function SetToolConfigPath(arg1:string,arg2:string):Promise<main.ToolConfigStatus>;

export function SetToolModel(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ToolConfigStatus>;

export function StartProxy():Promise<main.ProxyStatus>;

export function StopProxy():Promise<main.ProxyStatus>;

export function TestProviderConnection(arg1:string,arg2:string):Promise<main.ConnectionTestResult>;

export function UpsertProvider(arg1:main.Provider):Promise<Array<main.Provider>>;
