// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyDeepSeekClaudeCode(arg1) {
  return window['go']['main']['App']['ApplyDeepSeekClaudeCode'](arg1);
}

export function ApplyProxyToCodex(arg1, arg2) {
  return window['go']['main']['App']['ApplyProxyToCodex'](arg1, arg2);
}

export function ApplyToolModel(arg1) {
  return window['go']['main']['App']['ApplyToolModel'](arg1);
}

export function BackupDefaultConfig(arg1, arg2) {
  return window['go']['main']['App']['BackupDefaultConfig'](arg1, arg2);
}

export function ClearDefaultBackup(arg1) {
  return window['go']['main']['App']['ClearDefaultBackup'](arg1);
}

export function ClearToolConfigPath(arg1) {
  return window['go']['main']['App']['ClearToolConfigPath'](arg1);
}

export function ClearUsageStats() {
  return window['go']['main']['App']['ClearUsageStats']();
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function DiscoverToolConfigs() {
  return window['go']['main']['App']['DiscoverToolConfigs']();
}

export function EnsureProxyRouting() {
  return window['go']['main']['App']['EnsureProxyRouting']();
}

export function FetchProviderModels(arg1, arg2) {
  return window['go']['main']['App']['FetchProviderModels'](arg1, arg2);
}

export function GetActiveGatewayModel(arg1) {
  return window['go']['main']['App']['GetActiveGatewayModel'](arg1);
}

export function GetProviderPackageStatuses() {
  return window['go']['main']['App']['GetProviderPackageStatuses']();
}

export function GetProxyConfig() {
  return window['go']['main']['App']['GetProxyConfig']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetToolConfig(arg1) {
  return window['go']['main']['App']['GetToolConfig'](arg1);
}

export function GetUsageStats() {
  return window['go']['main']['App']['GetUsageStats']();
}

export function InjectGateway(arg1) {
  return window['go']['main']['App']['InjectGateway'](arg1);
}

export function ListActiveGatewayModels() {
  return window['go']['main']['App']['ListActiveGatewayModels']();
}

export function ListModelGroups() {
  return window['go']['main']['App']['ListModelGroups']();
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function PickToolConfig(arg1) {
  return window['go']['main']['App']['PickToolConfig'](arg1);
}

export function ReadConfigText(arg1) {
  return window['go']['main']['App']['ReadConfigText'](arg1);
}

export function ReorderModelGroupRoutes(arg1, arg2) {
  return window['go']['main']['App']['ReorderModelGroupRoutes'](arg1, arg2);
}

export function RestoreCodexOriginalBases() {
  return window['go']['main']['App']['RestoreCodexOriginalBases']();
}

export function RestoreDefaultConfig(arg1) {
  return window['go']['main']['App']['RestoreDefaultConfig'](arg1);
}

export function RevealConfigPath(arg1) {
  return window['go']['main']['App']['RevealConfigPath'](arg1);
}

export function RollbackGateway(arg1) {
  return window['go']['main']['App']['RollbackGateway'](arg1);
}

export function SaveProviders(arg1) {
  return window['go']['main']['App']['SaveProviders'](arg1);
}

export function SaveProxyConfig(arg1) {
  return window['go']['main']['App']['SaveProxyConfig'](arg1);
}

export function SetActiveGatewayModel(arg1, arg2) {
  return window['go']['main']['App']['SetActiveGatewayModel'](arg1, arg2);
}

export function SetModelGroupRouteEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetModelGroupRouteEnabled'](arg1, arg2);
}

export function SetModelGroupRoutePriority(arg1, arg2) {
  return window['go']['main']['App']['SetModelGroupRoutePriority'](arg1, arg2);
}

export function SetToolConfigPath(arg1, arg2) {
  return window['go']['main']['App']['SetToolConfigPath'](arg1, arg2);
}

export function SetToolModel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetToolModel'](arg1, arg2, arg3, arg4);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function TestProviderConnection(arg1, arg2) {
  return window['go']['main']['App']['TestProviderConnection'](arg1, arg2);
}

export function UpsertProvider(arg1) {
  return window['go']['main']['App']['UpsertProvider'](arg1);
}
